//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы изменили язык интерфейса, изменения вступят в силу после перезагрузки приложения.
        /// </summary>
        internal static string Msg_ChangeLanguageRestartRequires {
            get {
                return ResourceManager.GetString("Msg_ChangeLanguageRestartRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP module {0} is not available.
        /// </summary>
        internal static string Msg_NoPing {
            get {
                return ResourceManager.GetString("Msg_NoPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP IP address is wrong.
        /// </summary>
        internal static string Msg_WrongIpAddress {
            get {
                return ResourceManager.GetString("Msg_WrongIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP port is wrong.
        /// </summary>
        internal static string MsgWrongPort {
            get {
                return ResourceManager.GetString("MsgWrongPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP ip address.
        /// </summary>
        internal static string Settings_EspIp {
            get {
                return ResourceManager.GetString("Settings_EspIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esp port.
        /// </summary>
        internal static string Settings_EspPort {
            get {
                return ResourceManager.GetString("Settings_EspPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project folder.
        /// </summary>
        internal static string Settings_ProjectFolder {
            get {
                return ResourceManager.GetString("Settings_ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected a system file, changing or deleting system file content may cause damaging application executed on ESP module. Are you sure?.
        /// </summary>
        internal static string WarningConfirmSysFileChangeOrDelete {
            get {
                return ResourceManager.GetString("WarningConfirmSysFileChangeOrDelete", resourceCulture);
            }
        }
    }
}
